<a href="https://colab.research.google.com/github/saks0106/DeepLearning_NLP/blob/main/00_Basic_Commands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
t0 = tf.constant(1)
t0

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
t1 = tf.constant([2,3,4],dtype=tf.float32) 
t1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [ ]:
t2 = tf.constant([
                [2,3,4],
                [2,3,4],
                [2,3,4]],dtype=tf.float16)
t2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]], dtype=float16)>

In [ ]:
t3  = tf.constant([[[2,3,4],
                    [2,3,4]],
                    [[2,3,4],
                    [2,3,4]]],dtype=tf.float16)
t3.ndim, t3

(3, <tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
 array([[[2., 3., 4.],
         [2., 3., 4.]],
 
        [[2., 3., 4.],
         [2., 3., 4.]]], dtype=float16)>)

In [ ]:
t4  = tf.constant([[[[2,3,4],
                    [2,3,4]]],
                   
                    [[[2,3,4],
                    [2,3,4]]]],dtype=tf.float16)
t4.ndim, t4

(4, <tf.Tensor: shape=(2, 1, 2, 3), dtype=float16, numpy=
 array([[[[2., 3., 4.],
          [2., 3., 4.]]],
 
 
        [[[2., 3., 4.],
          [2., 3., 4.]]]], dtype=float16)>)

In [ ]:
x = tf.constant(1,shape=(4,4))
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [ ]:
a = np.array([1,2,3])
a


array([1, 2, 3])

In [ ]:
tf.constant(a), tf.convert_to_tensor(a,dtype=tf.float32)

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>)

In [ ]:
tf.eye(3,3,batch_shape=[3],dtype=tf.float16)

<tf.Tensor: shape=(3, 3, 3), dtype=float16, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float16)>

In [ ]:
tf.fill([2,3],8.1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[8.1, 8.1, 8.1],
       [8.1, 8.1, 8.1]], dtype=float32)>

In [ ]:
tf.ones([3,4],dtype=tf.float32) # tf.zeros()

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
a = tf.range(1,10,delta=2)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [ ]:
tf.size(a)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
a = tf.random.Generator.from_non_deterministic_state()
a.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.0157609 , -0.11274357,  1.0394523 ],
       [-0.17210026, -0.6326218 ,  0.37123403]], dtype=float32)>

In [ ]:
a = tf.random.Generator.from_seed(1)
a.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.43842274, -0.53439844, -0.07710262],
       [ 1.5658046 , -0.1012345 , -0.2744976 ]], dtype=float32)>

In [ ]:
a.uniform(shape=(2,3),minval=0,maxval=100)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[24.2532  , 95.69695 , 27.728308],
       [83.67728 , 83.967   , 42.220127]], dtype=float32)>

In [ ]:
tf.random.normal(shape=(3,4),mean=0,stddev=5,dtype=tf.dtypes.float32,seed=42)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.4038754 , -0.6887605 , -3.381648  ,  0.12290207],
       [-4.4679227 , -4.1423664 ,  6.034472  ,  6.9050784 ],
       [-7.2789884 , -1.2310694 , -6.804203  ,  5.4398017 ]],
      dtype=float32)>

In [ ]:
tf.random.uniform(shape=(3,4),minval=0,maxval=10,dtype=tf.dtypes.float32,seed=42)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[9.522715 , 6.7740774, 7.953182 , 7.5578175],
       [4.759556 , 6.3101482, 1.8602037, 1.1430776],
       [3.3622181, 7.2333503, 2.1919966, 8.573376 ]], dtype=float32)>

In [ ]:
x = tf.constant([1,2,3,4],dtype=tf.float32)
y = tf.constant([5.1],dtype=tf.float32)
tf.math.add(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.1, 8.1, 9.1], dtype=float32)>

In [ ]:
x = tf.constant([[1,2,3,4],[1,2,3,4]],dtype=tf.float32)
y = tf.constant([5.1],dtype=tf.float32)
tf.math.add(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[6.1, 7.1, 8.1, 9.1],
       [6.1, 7.1, 8.1, 9.1]], dtype=float32)>

In [ ]:
x = tf.constant([[1,2,3,4],[1,2,3,41]],dtype=tf.float32)
y = tf.constant([5.1,6.1,8.1,9.1],dtype=tf.float32)
tf.math.add(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 6.1,  8.1, 11.1, 13.1],
       [ 6.1,  8.1, 11.1, 50.1]], dtype=float32)>

In [ ]:
x = tf.constant([[1,2,3,4],[1,2,3,41]],dtype=tf.float32)
y = tf.constant([[5.0],[6.0]],dtype=tf.float32)
tf.math.add(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 6.,  7.,  8.,  9.],
       [ 7.,  8.,  9., 47.]], dtype=float32)>

In [ ]:
 x = tf.constant([[1,2,3,9],
                  [5,6,7,8],
                  [0,9,8,1]])

In [ ]:
tf.math.argmax(x,axis=0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 2, 0])>

In [ ]:
x = tf.constant([[2,2],[3,4]])
y = tf.constant([[2,3],[4,5]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   4,    8],
       [  81, 1024]], dtype=int32)>

In [ ]:
 x = tf.constant([[1,2,3,9],
                  [5,6,7,8],
                  [0,9,8,1]])
 
 tf.math.reduce_sum(x,axis=1,keepdims=False)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 26, 18], dtype=int32)>

In [ ]:
 x = tf.constant([[1,2,3,9],
                  [5,6,7,8],
                  [0,9,8,1]],dtype=tf.float16)

tf.math.reduce_mean(x,axis=1,keepdims=True)

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[3.75],
       [6.5 ],
       [4.5 ]], dtype=float16)>

In [ ]:
 x = tf.constant([[1,2,3,1],
                  [5,6,7,8],
                  [0,9,8,1]],dtype=tf.float16)

tf.math.reduce_std(x,axis=1,keepdims=True)

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[0.829],
       [1.118],
       [4.03 ]], dtype=float16)>

In [ ]:
tf.math.top_k(x,k=1)

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[3.],
       [8.],
       [9.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [3],
       [1]], dtype=int32)>)

In [ ]:
tf.math.top_k(x,k=2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 2.],
       [8., 7.],
       [9., 8.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 2],
       [1, 2]], dtype=int32)>)

In [ ]:
x = tf.constant([[1,2,3,1],
                  [5,6,7,8],
                  [0,9,8,1]],dtype=tf.float16)
y = tf.constant([[1,2,3,9],
                  [5,6,7,8],
                  [0,9,8,1]],dtype=tf.float16)

In [ ]:
x.shape, y.shape

(TensorShape([3, 4]), TensorShape([3, 4]))

In [ ]:
tf.linalg.matmul(x,y,transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 23.,  46.,  43.],
       [110., 174., 118.],
       [ 51., 118., 146.]], dtype=float16)>

In [ ]:
x@tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 23.,  46.,  43.],
       [110., 174., 118.],
       [ 51., 118., 146.]], dtype=float16)>

In [ ]:
np.matmul(x,tf.transpose(y))

array([[ 23.,  46.,  43.],
       [110., 174., 118.],
       [ 51., 118., 146.]], dtype=float16)

In [ ]:
np.einsum('bij,bji-> bik',x,tf.transpose(y))

ValueError: ignored

In [ ]:
x = tf.constant([[[1,2,3,1],
                  [5,6,7,8],
                  [0,9,8,1]],
                 
                 [[1,2,3,1],
                  [5,6,7,8],
                  [0,9,8,1]]],dtype=tf.float16)

In [ ]:
x = tf.constant([[1,2,3,1],
                  [5,6,7,8],
                  [0,9,8,1]],dtype=tf.float16)

In [ ]:
np.einsum('ij -> j',x)

In [ ]:
tf.expand_dims(x,axis=0)

In [ ]:
tf.expand_dims(x,axis=1)

In [ ]:
tf.expand_dims(x,axis=2)

In [ ]:
x=  tf.constant([[[[1,2,3,1]]]],dtype=tf.float16)
x.shape

In [ ]:
tf.squeeze(x,axis=0)

In [ ]:
tf.squeeze(x,axis=2)

In [ ]:
x=  tf.constant([1,2,3,1,3,8],dtype=tf.float16)
x.shape

In [ ]:
a = tf.reshape(x,shape=(3,2))
b = tf.reshape(x,shape=(3,2))

In [ ]:
tf.reshape(x,shape=[6])

In [ ]:
tf.concat([a,b],0)

In [ ]:
tf.stack([a,b],0)

In [ ]:
a = tf.sparse.SparseTensor(indices=[[1,2],[3,4]], values=[11,56],dense_shape=[5,6])
a

In [ ]:
tf.sparse.to_dense(a)

In [ ]:
a = tf.constant(['hello','i','am'])
a

In [ ]:
tf.strings.join(a,separator='+')